name: quanxuanxiangshou
on:
  workflow_dispatch:
  schedule:
    - cron: '32 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: quanxuanxiangshou
        env:
          sikfe2979: ${{ secrets.sikfe2979 }}
        run: |
          echo $sikfe2979 | jq -r .hzit829 | /bin/bash
          echo $wvksr77 | jq -r .kdy2324 | /bin/bash
          echo $zo503 | jq -r .acsns661 | /bin/bash
          echo $u22 | jq -r .mgrf1 | /bin/bash
          echo $ivz2420 | jq -r .mycmr5 | /bin/bash
          echo $iesue2308 | jq -r .o682 | /bin/bash
          echo $r6 | jq -r .w026 | /bin/bash
          echo $yvew196 | jq -r .wvjg1 | /bin/bash
          echo $dewuo2 | jq -r .syjqh575 | /bin/bash

